# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Reference A - No external dependencies
  - package-ecosystem: "nuget"
    directory: "/Reference A - No external dependencies/net6.0"
    schedule: { interval: "weekly" }
    groups: { dependencies: { patterns: ["*"] } }
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Authentication.JwtBearer"
        versions: ["[7,)"]
      - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
        versions: ["[7,)"]

  - package-ecosystem: "nuget"
    directory: "/Reference A - No external dependencies/net7.0"
    schedule: { interval: "weekly" }
    groups: { dependencies: { patterns: ["*"] } }

  - package-ecosystem: "nuget"
    directory: "/Reference A - No external dependencies/net8.0"
    schedule: { interval: "weekly" }
    groups: { dependencies: { patterns: ["*"] } }

  # Reference C - External HTTP API
  - package-ecosystem: "nuget"
    directory: "/Reference C - External HTTP API/net6.0"
    schedule: { interval: "weekly" }
    groups: { dependencies: { patterns: ["*"] } }
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
        versions: ["[7,)"]

  - package-ecosystem: "nuget"
    directory: "/Reference C - External HTTP API/net7.0"
    schedule: { interval: "weekly" }
    groups: { dependencies: { patterns: ["*"] } }

  - package-ecosystem: "nuget"
    directory: "/Reference C - External HTTP API/net8.0"
    schedule: { interval: "weekly" }
    groups: { dependencies: { patterns: ["*"] } }
