name: Build and Test

on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**/*.md"]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        folder:
          - Reference A - No external dependencies
        subfolder:
          - net6.0
          - net7.0
          - net8.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ${{ matrix.folder }}/${{ matrix.subfolder }}/global.json
      - name: Restore dependencies
        working-directory: ${{ matrix.folder }}/${{ matrix.subfolder }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ matrix.folder }}/${{ matrix.subfolder }}
        run: dotnet build --no-restore
      - name: Test
        working-directory: ${{ matrix.folder }}/${{ matrix.subfolder }}
        run: dotnet test --no-build --verbosity normal
        env:
          SNAPSHOOTER_STRICT_MODE: true
