name: Build and Test

on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**/*.md"]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        solution_folder:
          - Reference A - No external dependencies/net6.0
          - Reference A - No external dependencies/net7.0
          - Reference A - No external dependencies/net8.0
          - Reference B - Entity Framework Core/net6.0
          - Reference C - External HTTP API/net6.0
          - Reference C - External HTTP API/net7.0
          - Reference C - External HTTP API/net8.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ${{ matrix.solution_folder }}/global.json
      - name: Restore dependencies
        working-directory: ${{ matrix.solution_folder }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ matrix.solution_folder }}
        run: dotnet build --no-restore
      - name: Test
        working-directory: ${{ matrix.solution_folder }}
        run: dotnet test --no-build --verbosity normal
        env:
          SNAPSHOOTER_STRICT_MODE: true
